### ISSUE TITLE
Running tensorflow demo issue

### ISSUE THREAD

**Issue by ilyanelken** [SkafteNicki/libcpab#1]
Hi,
I am trying to run tensorflow demos, and encounter the following error:

""Traceback (most recent call last):
  File "tensorflow_demo3.py", line 8, in <module>
    from libcpab.tensorflow import cpab
  File "/media/ilyan/DATA/ilyan/code/libcpab/libcpab/tensorflow/__init__.py", line 8, in <module>
    from .cpab import cpab
  File "/media/ilyan/DATA/ilyan/code/libcpab/libcpab/tensorflow/cpab.py", line 17, in <module>
    from .cpab1d.transformer import tf_cpab_transformer_1D
  File "/media/ilyan/DATA/ilyan/code/libcpab/libcpab/tensorflow/cpab1d/transformer.py", line 27, in <module>
    transformer_op, grad_op = load_dynamic_modules()
  File "/media/ilyan/DATA/ilyan/code/libcpab/libcpab/tensorflow/cpab1d/transformer.py", line 21, in load_dynamic_modules
    transformer_module = tf.load_op_library(dir_path + '/./CPAB_ops.so')
  File "/home/ilyan/anaconda3/envs/ilyan_tf/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /media/ilyan/DATA/ilyan/code/libcpab/libcpab/tensorflow/cpab1d/./CPAB_ops.so: undefined symbol: _ZN10tensorflow12OpDefBuilder5InputESs
""

I have recompiled the cpab[1-3]d .so files.
My TF version is 1.13 and the cuda is 10.0 (os ubuntu 18.04)

I will appreciate your help.
Thanks

**Comment by SkafteNicki** [comment]
This probably has something to do with a mismatch in the gcc and tensorflow version you have installed. Can you supply the output of the command:
```gcc --version```

**Comment by ilyanelken** [comment]
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

But I see that the following line is present in Makefile:
"""-D_GLIBCXX_USE_CXX11_ABI=0"""
So the gcc version above 5.0 should work, right?

**Comment by SkafteNicki** [comment]
Yes, that is also how I understand the flag.
Could you try to downgrading your tensorflow (do it in a conda env) to 1.4. 
That was the last version I am sure libcpab works with.

**Comment by ilyanelken** [comment]
I have downgraded to TF 1.8  and managed to build the *.so with gcc-4.8.
Thanks for help

**Comment by experiment-designer** [comment]
I also had the same bug and solved it by downgrading TF 1.14 -> 1.11
