### ISSUE TITLE
Inverting the transformation

### ISSUE THREAD

**Issue by sagniklp** [SkafteNicki/libcpab#9]
Could you help me modify the code to compute the inverse transform?

**Comment by sorenhauberg** [comment]
To invert a transformation, you simply change the sign of the parameter vector.

Sent from Android Phone

28. jul. 2021 16.17 skrev Sagnik Das ***@***.***>:

Could you help me modify the code to compute the inverse transform?

**Comment by sagniklp** [comment]
Thanks!
